services:

  mongodb:
    image: mongo:7
    container_name: financialcontrol-mongodb

    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: FinancialControlDb

    volumes:
      - mongodb_data:/data/db

    networks:
      - financial-network

  rabbitmq:
    image: rabbitmq:3-management

    container_name: financialcontrol-rabbitmq

    restart: unless-stopped

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

    networks:
      - financial-network

volumes:

  mongodb_data:

networks:

  financial-network:
